name: storagereview
favicon: null
layout_spectrum: 0.92629
typography_spectrum: 0.60359
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#e9e9eb'
    - '#ff6a8d'
    - '#7f777a'
    - '#ff0038'
  brandStrength: 1
  lightness: 0.986020638840273
  saturation: 0.125
  rhythmicContrast: 0.21134211076423526
purpose: []
